### ISSUE TITLE
Close the database from python client

### ISSUE THREAD

**Issue by pkpro** [epsilla-cloud/vectordb#135]
**Describe the feature**
- Close the database from the Python client.

**Motivation and use case**
- I have a huge file with sentences (CCMatrix.en), and I want to put each sentence with its vector in a table. However, I do not have enough RAM to put 1.3B sentences into a single database. The OOM-Killer will wreak havoc on the Docker container and some other stuff. I can have several database instances where I can put these sentences and work with one database at a time. However, I can't be sure that the next database I open will have enough RAM if I didn't close the previous one.

**Additional context**
- Sure, I can start/stop the containers for each database and manage these starts/stops from the Python code, but this does not feel right.

**Comment by richard-epsilla** [comment]
Hi pkpro, does unload_db work for your use case? It will release the DB from memory but keep the data: https://epsilla-inc.gitbook.io/epsilladb/vector-database/delete-a-database#unload-a-database-using-epsilla-docker
It’s good suggestion we could rename it to close DB for batter convention

**Comment by pkpro** [comment]
Thank you a lot for this hint. It is working as expected. You do not need to change the current API though.

Something like this wrapper solves the open/close within the 'with' semantics:

```python
class epsillavdb():
  def __init__(self,host="localhost", port="8888", dbname="", db_path=f"/data/epsilla/", dbscale=150000, wal_enabled=True):
    self.host = host
    self.port = port
    self.dbname = dbname
    self.dbscale = dbscale
    self.wal_enabled = wal_enabled
    self.db_path = f"/data/epsilla/{self.dbname}"
    self.conn=vectordb.Client(host=self.host, port=self.port)
    if self.conn is None:
      raise Exception(f"Connection to database {self.dbname} failed")
  def __enter__(self):
    status_code, response = self.conn.load_db(db_name=self.dbname, db_path=self.db_path, vector_scale=self.dbscale, wal_enabled=self.wal_enabled)
    if status_code != 200:
      raise Exception(f"Error [{status_code}]. Can't use the database {self.dbname}, Epsilla response: {response}")
    else:
      print(f"DB is loaded: [{status_code}]. Epsilla response: {response}")
    self.conn.use_db(db_name=self.dbname)
    return self
  def __exit__(self, exc_type, exc_val, exc_tb):
    status_code, response = self.conn.unload_db(db_name=self.dbname)
    print(f"Unload DB {self.dbname}: {status_code}]. Epsilla response: {response}")
  def insert(self,table_name="",records=""):
    return self.conn.insert(table_name=table_name,records=records)
  def create_table(self,table_name="",table_fields="", indices=[]):
    return self.conn.create_table(table_name=table_name,table_fields=table_fields,indices=indices)

```

Usage:
```python
with epsillavdb(host=args.host, port=args.port, dbname=f"{args.dbpfx}_{dbcount}", dbscale=args.db_scale, wal_enabled=False) as epsilla_client:
      print(f"with sentence before insert")
      status_code, response = epsilla_client.insert(
        table_name="sentences",
        records=data
      )
      ...
```
