### ISSUE TITLE
BIGINT primary key being interpreted as a float when returning query

### ISSUE THREAD

**Issue by ThatOneShortGuy** [epsilla-cloud/vectordb#57]
The table used is the format with Python
```python
client.create_table(
    table_name='MyTable',
    table_fields=[
        {'name': 'MessageID', 'dataType': 'BIGINT', 'primaryKey': True},
        {'name': 'PixelVec' , 'dataType': 'VECTOR_FLOAT', 'dimensions': 100*100*3}
    ]
)
```

After calling 
```python
status, response = client.query(
    table_name='MyTable',
    query_field='PixelVec',
    query_vector=myVec,
)
```
the `response[0]['MessageID']` is some float or double
It is 1.157567399403463e+18 when it should be 1157567399403462676.
They are very close, just not quite there. After calling `int(1.157567399403463e+18)` I get 1157567399403462912. Only the last 3 digits are off, but it makes that makes it unusable.

I wanted to use the MessageID to retrieve the actual message, but this just isn't possible with such a response..

If you need/want any more information, please let me know.

**Comment by richard-epsilla** [comment]
Thanks for reporting! We are on it

**Comment by richard-epsilla** [comment]
@ThatOneShortGuy we fixed the bug, please pull docker again and retry

**Comment by ThatOneShortGuy** [comment]
The fix worked! Thanks for getting it to work.
