### ISSUE TITLE
setting oat++ paths

### ISSUE THREAD

**Issue by jmikedupont2** [epsilla-cloud/vectordb#77]
Hi there, 
I installed oat++ from git so I set the cmakelists like this
IMPORTED_LOCATION "/usr/local/lib/oatpp-1.3.0/liboatpp.a"                                          INTERFACE_INCLUDE_DIRECTORIES "/usr/local/include/oatpp-1.3.0/oatpp/"

**Comment by richard-epsilla** [comment]
Hi @jmikedupont2, to better assist you, could you please specify what issues you are encountering with the current CMakeLists configuration? Are you receiving any error messages during compilation or is the library not being found correctly?"

**Comment by jmikedupont2** [comment]
Oh i am fine, was just documenting the steps. thanks
