### ISSUE TITLE
not localhost

### ISSUE THREAD

**Issue by jmikedupont2** [epsilla-cloud/vectordb#79]
The server says its is listening on localhost but it is listining on 0.0.0.0 not 127.0.0.1 that is confusing. 
std::cout << "Server running on http://localhost:" << port << std::endl;

**Comment by eric-epsilla** [comment]
@jmikedupont2 will align the content of stdout to 0.0.0.0

**Comment by richard-epsilla** [comment]
Fixed in https://github.com/epsilla-cloud/vectordb/pull/80
