### ISSUE TITLE
Handle"already exists" errors in load_db calls gracefully, or with HTTP 409 

### ISSUE THREAD

**Issue by tonyyanga** [epsilla-cloud/vectordb#93]
When using Epsilla database with the docker image, we are required to use `load_db` method to load the database. The returned status code is HTTP 500 when the db is already loaded by the server. This could happen during normal operations, when multiple clients connect to the same db server.

It causes the clients to handle it with string matches on the error message.

```
if status_code != HTTPStatus.OK:
                if status_code == HTTPStatus.INTERNAL_SERVER_ERROR and (
                    "Database catalog file is already loaded" in response["message"]
                    or "DB already exists" in response["message"]
                ):
                    self._logger.info(f'{self._db_config.db_name} already loaded.')
                else:
                    raise IOError(
                        f"Failed to load database {self._db_config.db_name}. "
                        f"Error code: {status_code}. Error message: {response}."
                    )
```

It is better if the server / client library returns HTTP 200. Alternatively, the right HTTP status code (HTTP 409) should be used to avoid string matches on the error message.

It should require a simple change to this section of the code:

https://github.com/epsilla-cloud/vectordb/blob/2139141281c54f3588026555cb288a73aea47675/engine/db/catalog/basic_meta_impl.cpp#L185-L194

**Comment by richard-epsilla** [comment]
Thanks for the reporting! Will get it fixed today

**Comment by richard-epsilla** [comment]
@tonyyanga fixed in https://github.com/epsilla-cloud/vectordb/pull/95
